version: "3.9"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mongo

  celery_worker:
    build:
      context: ./backend
    command: celery -A app.celery_app.celery_app worker --loglevel=info
    depends_on:
      - redis
      - mongo

  beat:
    build: ./backend
    command: celery -A app.celery_app.celery_app beat --loglevel=info
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"

