kind: Service
apiVersion: v1
metadata:
  name: mongo
  labels:
    app: mongodb
spec:
  ports:
    - name: 27017-tcp
      protocol: TCP
      port: 27017
      targetPort: 27017
  internalTrafficPolicy: Cluster
  type: ClusterIP
  selector:
    app: mongodb
    deployment: mongodb

